baseURL = 'https://mxcitali.github.io/Paradigmas/'
languageCode = 'en-us'
title = 'Portafolio de Paradigmas'
theme = 'ananke'

[params]
  mainSections = ["practica0", "practica1", "practica2", "practica3", "practica4"]
  recent_posts_number = 10
