baseURL = 'https://mxcitali.github.io/Paradigmas/'
languageCode = 'en-us'
title = 'Portafolio de Paradigmas'
theme = 'ananke'

[params]
  mainSections = ["Practica0", "Practica1", "Practica2", "Practica3", "Practica4"]
  recent_posts_number = 10
